### ISSUE TITLE
  About Performance in High Speed Sports

### ISSUE THREAD

**Issue by 19855179496** [zijiechenrobotics/ig_lio#10]
May I ask how this algorithm performs in high-speed motion (20m/s), what is its pose error, and is its accuracy sufficient...

**Comment by zijiechenrobotics** [comment]
Thank you for your interest in this work. This is a good question!
I verified iG-LIO's accuracy on the Apollo dataset: https://developer.apollo.auto/daoxianglake.html. However, this experiment was removed due to the page limitation of RA-L.

The speed of the dataset was around 10~14 m/s, not 20m/s. The results are listed as follows:

**RPE per100 meters and time(ms)**
|             Seq             |  iG-LIO(RPE / time)   |  Faster-LIO   |     FastLIO2      | Dist(km) |
| :-------------------------: | :-------------------: | :-----------: | :---------------: | :------: |
| daoxianglake_20190924124848 | **0.096** / **18.12** | 0.109 / 24.71 |   0.101 / 46.42   |  47.973  |
| daoxianglake_20191014142530 | **0.097** / **18.88** | 0.102 / 25.33 | **0.097** / 47.31 |  27.825  |
| daoxianglake_20191021162130 |   0.092 / **18.45**   | 0.096 / 26.24 | **0.087** / 48.00 |  41.013  |
| daoxianglake_20191025104732 | **0.092** / **18.42** | 0.094 / 26.06 | **0.092** / 47.41 |  18.734  |
| daoxianglake_20191225153609 | **0.076** / **18.52** | 0.086 / 28.04 |   0.087 / 47.40   |  21.45   |

I think iG-LIO can work well as long as the following conditions are met:
1. The movement of the sensing system should not exceed the range of the IMU
2. The environment is not extremely narrow or lack of geometric features.

I hope these experiment results and suggestions will help you :smile:
